---
jobs:
- name: deploy-as-development
  serial: true
  plan:
  - in_parallel:
    - get: app-autoscaler-release
#      trigger: true
    - get: autoscaler-manifests
      resource: autoscaler-manifests
      trigger: true
    - get: terraform-yaml
      resource: terraform-yaml-development
    - get: cf-stemcell-jammy
      trigger: true
  - task: terraform-secrets
    file: autoscaler-manifests/ci/terraform-secrets.yml
  - put: cf-deployment-development
    params: &deploy-params
      manifest: templates/app-autoscaler.yml
      stemcells:
      - cf-stemcell-jammy/*.tgz
      ops_files:
      - router-main/router_main.yml
      - app-autoscaler-release/operations/rename-network-and-deployment.yml
      - autoscaler-manifests/bosh/opsfiles/use-s3-blobstore.yml
      - app-autoscaler-release/operations/use-external-dbs.yml
      - app-autoscaler-release/operations/stop-skipping-tls-validation.yml
      - app-autoscaler-release/operations/set-bbs-active-key.yml
      - app-autoscaler-release/operations/enable-service-discovery.yml
      - autoscaler-manifests/bosh/opsfiles/remove-routing-components-for-transition.yml
      - autoscaler-manifests/bosh/opsfiles/add-autoscaler-client.yml
      vars_files:
      - autoscaler-manifests/bosh/varsfiles/development.yml
      - terraform-secrets/terraform.yml


resources:
- name: app-autoscaler-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/app-autoscaler-release
    branch: main
    tag_filter: "v*"

- name: autoscaler-manifests
  type: git
  source:
    uri: https://github.com/cloud-gov/cg-deploy-autoscaler.git
    branch: main
    paths:
    - ci/*
    - bosh/*

- name: terraform-yaml-development
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file-development))
    region_name: ((aws-region))


- name: cf-stemcell-jammy
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-jammy-go_agent


- name: autoscaler-deployment-development
  type: bosh-deployment
  source:
    target: ((development-bosh-target))
    client: ((development-bosh-client))
    client_secret: ((development-bosh-client-secret))
    ca_cert: ((bosh-ca-cert))
    deployment: app-autoscaler